apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    app: bankapp
    version: blue # This can be changed to "green" when switching traffic
